spring.application.name=agendador-tarefas
spring.data.mongodb.uri=mongodb://localhost:27017/db_agendador
# mongodb:// > protocolo
# localhost  > onde o banco está rodando
# 27017      > porta padrão do Mongo
# db_agendador > nome do banco

usuario.url=localhost:8080
# URL base da API de usuário.
# Essa linha é usada aqui:
# @FeignClient(name = "usuario", url = "${usuario.url}")

server.port=8081
# Em microserviços, cada aplicação é independente
#  e precisa de sua própria porta para rodar no mesmo host.